project:
  type: website
  output-dir: docs
  post-render: ./post-build.sh
  preview:
    port: 7779

website:
  title: "ARG"
  favicon: images/logos/logoB.png
  navbar:
    title: false
    logo: images/logos/logoB2.png
    right:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Sobre mí
      - href: publications.qmd
        text: Publicaciones
      - href: blog.qmd
        text: Blog
      - href: CV.qmd
        text: CV
  cookie-consent: 
    type: implied
    style: simple
    palette: light
    language: es
    prefs-text: "Configuración de Cookies"
  google-analytics: 
    tracking-id: "G-YVC0YB78PW"
    anonymize-ip: true
  page-footer: 
    left: Copyright 2024, Alejandro Romero González
    right: Este sitio web está construido con [Quarto](https://quarto.org/)

format:
  html:
    theme:
      - tema_personalizado.scss
    mainfont: "Inter Tight"
    toc: true



