project:
  type: website
  output-dir: docs
  post-render: ./post-build.sh

website:
  title: "ARG"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Sobre mí
      - href: CV.qmd
        text: CV

format:
  html:
    theme: united
    css: styles.css
    toc: true



