project:
  type: website
  output-dir: docs

website:
  title: "ARG"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: united
    css: styles.css
    toc: true



