project:
  type: website
  output-dir: docs
  post-render: ./post-build.sh

website:
  title: "ARG"
  favicon: images/logos/logoB.png
  navbar:
    title: false
    logo: images/logos/logoB2.png
    right:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Sobre mí
      - href: publications.qmd
        text: Publicaciones
      - href: blog.qmd
        text: Blog
      - href: CV.qmd
        text: CV
  google-analytics: "G-YVC0YB78PW"
  page-footer: 
    left: Copyright 2023, Alejandro Romero González
    right: Este sitio web está construido con [Quarto](https://quarto.org/)

format:
  html:
    theme:
      - tema_personalizado.scss
    mainfont: "Inter Tight"
    toc: true



