---
title: "Sobre mí"
page-layout: full
title-block-banner: true
---

Bienvenid@ a mi espacio personal, un rincón digital donde convergen mi vida profesional y mis aspiraciones. Soy Alejandro Romero González, un economista y técnico en programación de sólida formación académica proveniente del [Centro de Investigación y Docencia Económicas](https://www.cide.edu/) y del [Instituto Politécnico Nacional](https://www.cecyt9.ipn.mx/), respectivamente. Mi trayectoria está marcada por una constante búsqueda de conocimiento y una innata habilidad para el análisis y la solución de problemas complejos.

La programación no es solo una pieza de mi herramental técnico, es una extensión de mi pensamiento crítico. Con un dominio avanzado de R y Python y una comprensión básica de Stata, mi enfoque es siempre multifacético. Herramientas como MySQL, Git, Quarto y QGIS se han convertido en mis compañeros ocasionales en la exploración y manipulación de datos.

Mi pasión por compartir conocimientos me ha llevado a roles de mentoría y docencia, donde la difusión de educación de calidad es mi bandera. Como Profesor y Coordinador General en [IncluCIDE](https://www.facebook.com/IncluCIDE), lideré esfuerzos para disminuir la disparidad educativa, brindando clases gratuitas de Matemáticas e Inglés para el empoderamiento y el éxito de jóvenes estudiantes provenientes de escuelas primarias y secundarias públicas de 16 estados de la república. Como Profesor Asistente en el CIDE, impartí el curso de Microeconomía II a 16 estudiantes de segundo año de la Licenciatura en Economía, bajo la supervisión de la [Dra. Sonia Di Giannatale](https://www.researchgate.net/profile/Sonia-Di-Giannatale). Mediante clases de 120 minutos, tareas y asignaciones propuestas por la profesora, fomenté un ambiente de aprendizaje colaborativo y enriquecedor para todos los estudiantes, logrando así una comprensión sólida de los conceptos revisados.

En cada conjunto de datos veo una historia esperando ser contada, y en cada desafío, una oportunidad para crecer. Esta perspectiva, alimentada por mi experiencia en docencia y programación, es la chispa detrás de mi [*blog*](blog.qmd). Ahí, fusiono mis habilidades analíticas y de enseñanza para ofrecer un viaje único a través del mundo de la economía y la ciencia de datos. Te invito a adentrarte en este viaje conmigo, donde exploraremos juntos distintas herramientas, compartiremos ideas innovadoras y descubriremos dichas historias ocultas.